[package]
name = "ard-r-sound"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.1.3", features = ["derive"] }
cpal = "0.14.2"
enum-iterator = "1.2.0"
fraction = "0.12.2"
pest = "2.0"
pest_derive = "2.0"
wav = "1.0.0"
